"""Models specific to the CUMULUS method."""

from typing import Any, Literal

from pydantic import BaseModel
from sqlmodel import JSON, Column, Field, SQLModel

from .generic import SolutionInfo
from .generic_states import SolutionReferenceResponse
from .preference import ReferencePoint


class CumulusClassificationRequest(SQLModel):
    """Request model for the CUMULUS solve endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    preference: ReferencePoint = Field(sa_column=Column(JSON))

    current_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="Current objective values for classification."
    )
    scalarizations: list[str] = Field(
        default_factory=lambda: ["cumulonimbus"],
        description="List of CumulusScalarization enum values as strings.",
    )


class CumulusInitializationRequest(SQLModel):
    """Request model for the CUMULUS initialization endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    name: str | None = Field(default=None, description="Optional name for the combined scenario problem.")
    starting_point: ReferencePoint | SolutionInfo | None = Field(sa_column=Column(JSON), default=None)
    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    uncertainty_measures: list["UncertaintyMeasureSpec"] | None = Field(sa_column=Column(JSON), default=None)


class CumulusSaveRequest(SQLModel):
    """Request model for saving CUMULUS solutions."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: list[SolutionInfo]


class CumulusDeleteSaveRequest(SQLModel):
    """Request model for deletion of a saved CUMULUS solution."""

    state_id: int = Field(description="The ID of the save state.")
    solution_index: int = Field(description="The index of the solution within the above state.")
    problem_id: int = Field(description="The ID of the problem.")
    original_problem_id: int | None = Field(default=None, description="The ID of the original problem.")


class CumulusFinalizeRequest(SQLModel):
    """Request model for finalizing the CUMULUS procedure."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: SolutionInfo


class CumulusClassificationResponse(SQLModel):
    """Response from the CUMULUS solve endpoint."""

    response_type: Literal["cumulus.classification"] = "cumulus.classification"

    state_id: int | None = Field(description="The newly created state id.")
    scenario_model_id: int | None = Field(
        default=None,
        description="DB id of the ScenarioModelDB used for augmentation, if the problem has scenarios.",
    )
    previous_preference: ReferencePoint = Field(description="The preference used in this iteration.")
    previous_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="The current objectives used for iteration."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="Solutions from the current CUMULUS iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Non-fatal warnings about the solve, e.g. a scalarization that failed due to active constraints.",
    )


class CumulusInitializationResponse(SQLModel):
    """Response from the CUMULUS initialization endpoint."""

    response_type: Literal["cumulus.initialization"] = "cumulus.initialization"

    state_id: int | None = Field(description="The newly created state id.")
    problem_id: int | None = Field(
        default=None,
        description=(
            "The problem ID actually used for initialization. "
            "Differs from the requested problem_id when a combined scenario problem was built on the fly."
        ),
    )
    current_solutions: list[SolutionReferenceResponse] = Field(description="The starting solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )
    hard_constraint_ids: list[int] = Field(
        default_factory=list,
        description="DB ids of the active hard objective constraints.",
    )
    soft_constraint_ids: list[int] = Field(
        default_factory=list,
        description="DB ids of the active soft objective constraints.",
    )


class CumulusSaveResponse(SQLModel):
    """Response from the CUMULUS save endpoint."""

    response_type: Literal["cumulus.save"] = "cumulus.save"

    state_id: int | None = Field(description="The id of the newest state.")


class CumulusDeleteSaveResponse(SQLModel):
    """Response from the CUMULUS delete-save endpoint."""

    response_type: str = "cumulus.delete_save"

    message: str | None = None


class CumulusFinalizeResponse(SQLModel):
    """Response from the CUMULUS finalize endpoint."""

    response_type: Literal["cumulus.finalize"] = "cumulus.finalize"

    state_id: int | None = Field(description="The newly created state id.")
    final_solution: SolutionReferenceResponse = Field(description="The final selected solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusIntermediateSolutionResponse(SQLModel):
    """Response from the Cumulus intermediate solutions endpoint."""

    response_type: Literal["cumulus.intermediate"] = "cumulus.intermediate"

    state_id: int | None = Field(description="The newly created state id.")
    reference_solution_1: dict[str, float] = Field(
        sa_column=Column(JSON), description="The first solution used when computing intermediate points."
    )
    reference_solution_2: dict[str, float] = Field(
        sa_column=Column(JSON), description="The second solution used when computing intermediate points."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The intermediate solutions from this iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by Cumulus across all iterations."
    )


class SoftConstraintSpec(BaseModel):
    """Specification for adding a constraint as a soft, penalty-based one.

    A constraint referenced here is never added as a hard constraint, even if it is also
    defined in this request's ``constraints`` list. Instead it is passed to
    ``add_soft_constraint``, which introduces non-negative slack variables that absorb
    violations and accumulates them into a minimisation objective.
    """

    constraint_symbol: str = Field(
        description=(
            "Symbol of the constraint to add as soft. Must be defined either in this request's "
            "'constraints' list or already present in the problem."
        )
    )
    violation_symbol: str = Field(
        default="constraint_violation", description="Symbol for the aggregated constraint-violation objective."
    )
    lte_violation_symbol: str | None = Field(default=None, description="Custom symbol for the LTE slack variable.")
    gte_violation_symbol: str | None = Field(
        default=None, description="Custom symbol for the GTE slack variable (EQ constraints only)."
    )


class UncertaintyMeasureSpec(BaseModel):
    """Specification for adding a scenario-based uncertainty aggregate to the problem.

    All measures in a single request must reference the same ``scenario_model_id``.
    The resulting combined (multi-scenario) problem replaces the current problem.
    """

    measure_type: Literal["expected_value", "worst_case_robust", "conditional_value_at_risk", "weighted_scenarios"] = (
        Field(description="Which uncertainty aggregate to apply.")
    )
    scenario_model_id: int = Field(description="DB id of the ScenarioModelDB that defines the scenario structure.")
    symbols: list[str] = Field(description="Symbols of objectives or functions to aggregate.")
    prefix: str | None = Field(
        default=None, description="Prefix for the new aggregate symbols. Defaults vary by measure_type."
    )
    alpha: float | None = Field(
        default=None, description="Confidence level for CVaR, e.g. 0.95. Required for conditional_value_at_risk."
    )
    leaf_weights: dict[str, float] | None = Field(
        default=None, description="Leaf-name → weight mapping. Required for weighted_scenarios."
    )


class ProblemModification(BaseModel):
    """Partial problem specification for modifying an existing problem.

    Each list entry is validated as the corresponding Problem element type.
    An element whose symbol matches an existing element of the same type replaces it.
    An element whose symbol matches an existing element of a *different* type is an error.
    Elements with a new symbol are added.
    """

    variables: list[Any] | None = None
    constants: list[Any] | None = None
    objectives: list[Any] | None = None
    constraints: list[Any] | None = None
    extra_funcs: list[Any] | None = None
    scalarization_funcs: list[Any] | None = None
    remove: list[str] | None = Field(
        default=None,
        description="Symbols of elements to remove from the problem. The element type is inferred automatically.",
    )
    soft_constraints: list[SoftConstraintSpec] | None = None
    uncertainty_measures: list[UncertaintyMeasureSpec] | None = None


class CumulusModificationRequest(SQLModel):
    """Request model for the CUMULUS modify-problem endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)
    name: str | None = Field(default=None, description="Optional name for the newly created modified problem.")

    modifications: ProblemModification = Field(sa_column=Column(JSON))


class CumulusModificationResponse(SQLModel):
    """Response from the CUMULUS modify-problem endpoint."""

    response_type: Literal["cumulus.modify"] = "cumulus.modify"

    state_id: int = Field(description="The newly created modification state id.")
    problem_id: int = Field(description="The ID of the newly created modified problem.")
    original_problem_id: int | None = Field(description="The ID of the original problem.")
    scenario_model_id: int | None = Field(
        default=None,
        description="DB id of the ScenarioModelDB associated with the original problem, if any.",
    )
    is_ready: bool = Field(
        default=False,
        description="False immediately after the endpoint returns; "
        "True once the background feasibility check completes.",
    )
    error: str | None = Field(default=None, description="Set if the background feasibility check failed.")


class CumulusScenarioSetupResponse(SQLModel):
    """Response when the problem has scenarios but no uncertainty measures have been chosen yet.

    The frontend should present this to the decision maker and let them choose which
    uncertainty aggregates to include, then re-call get-or-initialize with the chosen measures.
    """

    response_type: Literal["cumulus.scenario_setup"] = "cumulus.scenario_setup"
    scenario_model_id: int = Field(description="DB id of the ScenarioModelDB associated with this problem.")
    objective_symbols: list[str] = Field(description="Symbols of the objectives available for aggregation.")


class CumulusObjectiveConstraintRequest(SQLModel):
    """Request model for setting objective constraints in the CUMULUS method."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    hard_constraints: list[Any] = Field(
        sa_column=Column(JSON),
        default_factory=list,
        description="Hard objective constraints as ConstraintDB-compatible dicts. Replaces any previously stored list.",
    )
    soft_constraints: list[Any] = Field(
        sa_column=Column(JSON),
        default_factory=list,
        description="Soft objective constraints as ConstraintDB-compatible dicts. Replaces any previously stored list.",
    )


class CumulusObjectiveConstraintResponse(SQLModel):
    """Response from the CUMULUS objective-constraint endpoint."""

    response_type: Literal["cumulus.objective_constraint"] = "cumulus.objective_constraint"

    state_id: int = Field(description="The newly created state id.")
    hard_constraint_ids: list[int] = Field(description="DB ids of the hard ConstraintDB rows now in effect.")
    soft_constraint_ids: list[int] = Field(description="DB ids of the soft ConstraintDB rows now in effect.")
