"""Models specific to the CUMULUS method."""

from typing import Literal

from sqlmodel import JSON, Column, Field, SQLModel

from .generic import SolutionInfo
from .generic_states import SolutionReferenceResponse
from .preference import ReferencePoint


class CumulusClassificationRequest(SQLModel):
    """Request model for the CUMULUS solve endpoint."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    preference: ReferencePoint = Field(Column(JSON))

    current_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="Current objective values for classification."
    )
    scalarizations: list[str] = Field(
        default_factory=lambda: ["cumulonimbus"],
        description="List of CumulusScalarization enum values as strings.",
    )


class CumulusInitializationRequest(SQLModel):
    """Request model for the CUMULUS initialization endpoint."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    starting_point: ReferencePoint | SolutionInfo | None = Field(sa_column=Column(JSON), default=None)
    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)


class CumulusSaveRequest(SQLModel):
    """Request model for saving CUMULUS solutions."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: list[SolutionInfo]


class CumulusDeleteSaveRequest(SQLModel):
    """Request model for deletion of a saved CUMULUS solution."""

    state_id: int = Field(description="The ID of the save state.")
    solution_index: int = Field(description="The index of the solution within the above state.")
    problem_id: int = Field(description="The ID of the problem.")


class CumulusFinalizeRequest(SQLModel):
    """Request model for finalizing the CUMULUS procedure."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: SolutionInfo


class CumulusClassificationResponse(SQLModel):
    """Response from the CUMULUS solve endpoint."""

    response_type: Literal["cumulus.classification"] = "cumulus.classification"

    state_id: int | None = Field(description="The newly created state id.")
    previous_preference: ReferencePoint = Field(description="The preference used in this iteration.")
    previous_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="The current objectives used for iteration."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="Solutions from the current CUMULUS iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusInitializationResponse(SQLModel):
    """Response from the CUMULUS initialization endpoint."""

    response_type: Literal["cumulus.initialization"] = "cumulus.initialization"

    state_id: int | None = Field(description="The newly created state id.")
    current_solutions: list[SolutionReferenceResponse] = Field(description="The starting solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusSaveResponse(SQLModel):
    """Response from the CUMULUS save endpoint."""

    response_type: Literal["cumulus.save"] = "cumulus.save"

    state_id: int | None = Field(description="The id of the newest state.")


class CumulusDeleteSaveResponse(SQLModel):
    """Response from the CUMULUS delete-save endpoint."""

    response_type: str = "cumulus.delete_save"

    message: str | None = None


class CumulusFinalizeResponse(SQLModel):
    """Response from the CUMULUS finalize endpoint."""

    response_type: Literal["cumulus.finalize"] = "cumulus.finalize"

    state_id: int | None = Field(description="The newly created state id.")
    final_solution: SolutionReferenceResponse = Field(description="The final selected solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusIntermediateSolutionResponse(SQLModel):
    """Response from the Cumulus intermediate solutions endpoint."""

    response_type: Literal["cumulus.intermediate"] = "cumulus.intermediate"

    state_id: int | None = Field(description="The newly created state id.")
    reference_solution_1: dict[str, float] = Field(
        sa_column=Column(JSON), description="The first solution used when computing intermediate points."
    )
    reference_solution_2: dict[str, float] = Field(
        sa_column=Column(JSON), description="The second solution used when computing intermediate points."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The intermediate solutions from this iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by Cumulus across all iterations."
    )
