"""Models specific to the CUMULUS method."""

from typing import Any, Literal

from pydantic import BaseModel
from sqlmodel import JSON, Column, Field, SQLModel

from .generic import SolutionInfo
from .generic_states import SolutionReferenceResponse
from .preference import ReferencePoint


class CumulusClassificationRequest(SQLModel):
    """Request model for the CUMULUS solve endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    preference: ReferencePoint = Field(Column(JSON))

    current_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="Current objective values for classification."
    )
    scalarizations: list[str] = Field(
        default_factory=lambda: ["cumulonimbus"],
        description="List of CumulusScalarization enum values as strings.",
    )


class CumulusInitializationRequest(SQLModel):
    """Request model for the CUMULUS initialization endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    starting_point: ReferencePoint | SolutionInfo | None = Field(sa_column=Column(JSON), default=None)
    scalarization_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(sa_column=Column(JSON), default=None)


class CumulusSaveRequest(SQLModel):
    """Request model for saving CUMULUS solutions."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: list[SolutionInfo]


class CumulusDeleteSaveRequest(SQLModel):
    """Request model for deletion of a saved CUMULUS solution."""

    state_id: int = Field(description="The ID of the save state.")
    solution_index: int = Field(description="The index of the solution within the above state.")
    problem_id: int = Field(description="The ID of the problem.")
    original_problem_id: int | None = Field(default=None, description="The ID of the original problem.")


class CumulusFinalizeRequest(SQLModel):
    """Request model for finalizing the CUMULUS procedure."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: SolutionInfo


class CumulusClassificationResponse(SQLModel):
    """Response from the CUMULUS solve endpoint."""

    response_type: Literal["cumulus.classification"] = "cumulus.classification"

    state_id: int | None = Field(description="The newly created state id.")
    previous_preference: ReferencePoint = Field(description="The preference used in this iteration.")
    previous_objectives: dict[str, float] = Field(
        sa_column=Column(JSON), description="The current objectives used for iteration."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="Solutions from the current CUMULUS iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusInitializationResponse(SQLModel):
    """Response from the CUMULUS initialization endpoint."""

    response_type: Literal["cumulus.initialization"] = "cumulus.initialization"

    state_id: int | None = Field(description="The newly created state id.")
    current_solutions: list[SolutionReferenceResponse] = Field(description="The starting solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusSaveResponse(SQLModel):
    """Response from the CUMULUS save endpoint."""

    response_type: Literal["cumulus.save"] = "cumulus.save"

    state_id: int | None = Field(description="The id of the newest state.")


class CumulusDeleteSaveResponse(SQLModel):
    """Response from the CUMULUS delete-save endpoint."""

    response_type: str = "cumulus.delete_save"

    message: str | None = None


class CumulusFinalizeResponse(SQLModel):
    """Response from the CUMULUS finalize endpoint."""

    response_type: Literal["cumulus.finalize"] = "cumulus.finalize"

    state_id: int | None = Field(description="The newly created state id.")
    final_solution: SolutionReferenceResponse = Field(description="The final selected solution.")
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by CUMULUS across all iterations."
    )


class CumulusIntermediateSolutionResponse(SQLModel):
    """Response from the Cumulus intermediate solutions endpoint."""

    response_type: Literal["cumulus.intermediate"] = "cumulus.intermediate"

    state_id: int | None = Field(description="The newly created state id.")
    reference_solution_1: dict[str, float] = Field(
        sa_column=Column(JSON), description="The first solution used when computing intermediate points."
    )
    reference_solution_2: dict[str, float] = Field(
        sa_column=Column(JSON), description="The second solution used when computing intermediate points."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The intermediate solutions from this iteration."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="Candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by Cumulus across all iterations."
    )


class SoftConstraintSpec(BaseModel):
    """Specification for converting a regular constraint into a soft penalty-based one.

    After standard element modifications are applied, any constraint listed here is passed
    to ``add_soft_constraint``, which introduces non-negative slack variables that absorb
    violations and accumulates them into a minimisation objective.
    """

    constraint_symbol: str = Field(
        description="Symbol of the constraint to soften. Must exist in the problem after standard modifications."
    )
    violation_symbol: str = Field(
        default="constraint_violation", description="Symbol for the aggregated constraint-violation objective."
    )
    lte_violation_symbol: str | None = Field(default=None, description="Custom symbol for the LTE slack variable.")
    gte_violation_symbol: str | None = Field(
        default=None, description="Custom symbol for the GTE slack variable (EQ constraints only)."
    )


class UncertaintyMeasureSpec(BaseModel):
    """Specification for adding a scenario-based uncertainty aggregate to the problem.

    All measures in a single request must reference the same ``scenario_model_id``.
    The resulting combined (multi-scenario) problem replaces the current problem.
    """

    measure_type: Literal["expected_value", "worst_case_robust", "conditional_value_at_risk", "weighted_scenarios"] = (
        Field(description="Which uncertainty aggregate to apply.")
    )
    scenario_model_id: int = Field(description="DB id of the ScenarioModelDB that defines the scenario structure.")
    symbols: list[str] = Field(description="Symbols of objectives or functions to aggregate.")
    prefix: str | None = Field(
        default=None, description="Prefix for the new aggregate symbols. Defaults vary by measure_type."
    )
    alpha: float | None = Field(
        default=None, description="Confidence level for CVaR, e.g. 0.95. Required for conditional_value_at_risk."
    )
    leaf_weights: dict[str, float] | None = Field(
        default=None, description="Leaf-name → weight mapping. Required for weighted_scenarios."
    )


class ProblemModification(BaseModel):
    """Partial problem specification for modifying an existing problem.

    Each list entry is validated as the corresponding Problem element type.
    An element whose symbol matches an existing element of the same type replaces it.
    An element whose symbol matches an existing element of a *different* type is an error.
    Elements with a new symbol are added.
    """

    variables: list[Any] | None = None
    constants: list[Any] | None = None
    objectives: list[Any] | None = None
    constraints: list[Any] | None = None
    extra_funcs: list[Any] | None = None
    scalarization_funcs: list[Any] | None = None
    soft_constraints: list[SoftConstraintSpec] | None = None
    uncertainty_measures: list[UncertaintyMeasureSpec] | None = None


class CumulusModificationRequest(SQLModel):
    """Request model for the CUMULUS modify-problem endpoint."""

    problem_id: int
    original_problem_id: int | None = Field(default=None)
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    modifications: ProblemModification = Field(sa_column=Column(JSON))


class CumulusModificationResponse(SQLModel):
    """Response from the CUMULUS modify-problem endpoint."""

    response_type: Literal["cumulus.modify"] = "cumulus.modify"

    state_id: int = Field(description="The newly created modification state id.")
    problem_id: int = Field(description="The ID of the newly created modified problem.")
    original_problem_id: int | None = Field(description="The ID of the original problem.")
    is_ready: bool = Field(
        default=False,
        description="False immediately after the endpoint returns; True once the background feasibility check completes.",
    )
    error: str | None = Field(default=None, description="Set if the background feasibility check failed.")
