"""Functions related to the CUMULUS method.

References:
    TBD
"""

from enum import Enum

import numpy as np
import polars as pl

from desdeo.problem import (
    PolarsEvaluator,
    Problem,
    Variable,
    VariableType,
    flatten_variable_dict,
    unflatten_variable_array,
)
from desdeo.tools import (
    BaseSolver,
    SolverOptions,
    SolverResults,
    add_asf_diff,
    add_asf_nondiff,
    add_asf_partial_diff,
    add_asf_partial_nondiff,
    add_cumulonimbus_diff,
    guess_best_solver,
)


class CumulusError(Exception):
    """Raised when an error with a CUMULUS method is encountered."""


class CumulusScalarization(Enum):
    """Scalarization functions compatible with the CUMULUS method.

    All variants operate on a partial reference point — they only scalarize
    the objectives whose symbols appear in the reference point supplied to
    :func:`solve_sub_problems`.  Objectives absent from the reference point
    are left unconstrained.
    """

    CUMULONIMBUS = "cumulonimbus"
    """Partial NIMBUS scalarization (:func:`~desdeo.tools.add_cumulonimbus_diff`).

    Derives classifications from the reference point and current objective
    values, then builds NIMBUS-style improvement/reservation constraints only
    for the classified objectives.  Requires ideal and nadir to be defined for
    every objective present in the reference point.
    """

    ASF_PARTIAL_DIFF = "asf_partial_diff"
    """Partial differentiable ASF (:func:`~desdeo.tools.add_asf_partial_diff`).

    Minimizes a differentiable achievement scalarizing function over the subset
    of objectives in the reference point.  No classification step is performed.
    """

    ASF_PARTIAL_NONDIFF = "asf_partial_nondiff"
    """Partial non-differentiable ASF (:func:`~desdeo.tools.add_asf_partial_nondiff`).

    Same as :attr:`ASF_PARTIAL_DIFF` but uses an explicit ``Max`` operator in
    the objective function instead of an auxiliary variable, making it suitable
    for derivative-free solvers.
    """


def solve_intermediate_solutions(
    problem: Problem,
    solution_1: dict[str, VariableType],
    solution_2: dict[str, VariableType],
    num_desired: int,
    scalarization_options: dict | None = None,
    solver: BaseSolver | None = None,
    solver_options: SolverOptions | None = None,
) -> list[SolverResults]:
    """Generates a desired number of intermediate solutions between two given solutions.

    Generates a desires number of intermediate solutions given two Pareto optimal solutions.
    The solutions are generated by taking n number of steps between the two solutions in the
    objective space. The objective vectors corresponding to these solutions are then
    utilized as reference points in the achievement scalarizing function. Solving the functions
    for each reference point will project the reference point on the Pareto optimal
    front of the problem. These projected solutions are then returned. Note that the
    intermediate solutions are generated _between_ the two given solutions, this means the
    returned solutions will not include the original points.

    Args:
        problem (Problem): the problem being solved.
        solution_1 (dict[str, VariableType]): the first of the solutions between which the intermediate
            solutions are to be generated.
        solution_2 (dict[str, VariableType]): the second of the solutions between which the intermediate
            solutions are to be generated.
        num_desired (int): the number of desired intermediate solutions to be generated. Must be at least `1`.
        scalarization_options (dict | None, optional): optional kwargs passed to the scalarization function.
            Defaults to None.
        solver (BaseSolver | None, optional): solver used to solve the problem.
            If not given, an appropriate solver will be automatically determined based on the features of `problem`.
            Defaults to None.
        solver_options (SolverOptions | None, optional): optional options passed
            to the `solver`. Ignored if `solver` is `None`.
            Defaults to None.

    Returns:
        list[SolverResults]: a list with the projected intermediate solutions as
            `SolverResults` objects.
    """
    if int(num_desired) < 1:
        msg = f"The given number of desired intermediate ({num_desired=}) solutions must be at least 1."
        raise CumulusError(msg)

    init_solver = guess_best_solver(problem) if solver is None else solver
    _solver_options = None if solver_options is None or solver is None else solver_options

    # compute the element-wise difference between each solution (in the decision space)
    solution_1_arr = flatten_variable_dict(problem, solution_1)
    solution_2_arr = flatten_variable_dict(problem, solution_2)
    delta = solution_1_arr - solution_2_arr

    # the '2' is in the denominator because we want to calculate the steps
    # between the two given points; we are not interested in the given points themselves.
    step_size = delta / (2 + num_desired)

    intermediate_points = np.array([solution_2_arr + i * step_size for i in range(1, num_desired + 1)])

    intermediate_var_values = pl.DataFrame(
        [unflatten_variable_array(problem, x) for x in intermediate_points],
        schema=[
            (var.symbol, pl.Float64 if isinstance(var, Variable) else pl.Array(pl.Float64, tuple(var.shape)))
            for var in problem.variables
        ],
    )

    # evaluate the intermediate points to get reference points
    # TODO(gialmisi): an evaluator might have to be selected depending on the problem
    evaluator = PolarsEvaluator(problem)

    reference_points = (
        evaluator.evaluate(intermediate_var_values).select([obj.symbol for obj in problem.objectives]).to_dicts()
    )

    # for each reference point, add and solve the ASF scalarization problem
    # projecting the reference point onto the Pareto optimal front of the problem.
    # TODO(gialmisi): this can be done in parallel.
    intermediate_solutions = []
    for rp in reference_points:
        # add scalarization
        add_asf = add_asf_diff if problem.is_twice_differentiable else add_asf_nondiff
        asf_problem, target = add_asf(problem, "target", rp, **(scalarization_options or {}))

        solver = init_solver(asf_problem, _solver_options)

        # solve and store results
        result: SolverResults = solver.solve(target)

        intermediate_solutions.append(result)

    return intermediate_solutions


def infer_classifications(
    problem: Problem, current_objectives: dict[str, float], reference_point: dict[str, float]
) -> dict[str, tuple[str, float | None]]:
    r"""Infers CUMULUS classifications for the objectives present in ``reference_point``.

    Only the objectives whose symbols appear as keys in ``reference_point`` are
    classified.  Objectives absent from ``reference_point`` are left out of the
    returned dict and are treated as free by the scalarization functions.

    The following classifications are inferred for each active objective:

    - $I^{<}$: values that should improve, the reference point value of an objective
        function is equal to its ideal value;
    - $I^{\leq}$: values that should improve until a given aspiration level, the reference point
        value of an objective function is better than the current value;
    - $I^{=}$: values that should stay as they are, the reference point value of an objective
        function is equal to the current value;
    - $I^{\geq}$: values that can be impaired until some reservation level, the reference point
        value of an objective function is worse than the current value; and
    - $I^{\diamond}$: values that are allowed to change freely, the reference point value of
        and objective function is equal to its nadir value.

    Raises:
        CumulusError: any key in ``reference_point`` is not a valid objective symbol.
        CumulusError: any active objective is missing an ideal or nadir value.
        CumulusError: ``current_objectives`` is missing an entry for one or more active objectives.

    Args:
        problem (Problem): the problem the current objectives and the reference point
            are related to.
        current_objectives (dict[str, float]): objective values for the current solution.
            Must contain entries for every objective present in ``reference_point``.
        reference_point (dict[str, float]): partial or full objective dict with reference
            point values.  Only objectives whose symbols appear here are classified.

    Returns:
        dict[str, tuple[str, float | None]]: a dict whose keys are the symbols of the
            active objectives and whose values are ``(classification, level)`` tuples.
            The level is ``None`` unless the classification is ``"<="`` (aspiration) or
            ``">="`` (reservation).
    """
    valid_symbols = {obj.symbol for obj in problem.objectives}
    invalid = set(reference_point) - valid_symbols
    if invalid:
        msg = f"reference_point contains keys that are not objective symbols: {invalid}."
        raise CumulusError(msg)

    active_objectives = [obj for obj in problem.objectives if obj.symbol in reference_point]

    missing_ideal = [obj.symbol for obj in active_objectives if obj.ideal is None]
    missing_nadir = [obj.symbol for obj in active_objectives if obj.nadir is None]
    if missing_ideal or missing_nadir:
        msg = f"Active objectives are missing ideal values: {missing_ideal}, nadir values: {missing_nadir}."
        raise CumulusError(msg)

    missing_current = [obj.symbol for obj in active_objectives if obj.symbol not in current_objectives]
    if missing_current:
        msg = f"current_objectives is missing entries for active objectives: {missing_current}."
        raise CumulusError(msg)

    classifications = {}

    for obj in active_objectives:
        if np.isclose(reference_point[obj.symbol], obj.nadir):
            # the objective is free to change
            classification = {obj.symbol: ("0", None)}
        elif np.isclose(reference_point[obj.symbol], obj.ideal):
            # the objective should improve
            classification = {obj.symbol: ("<", None)}
        elif np.isclose(reference_point[obj.symbol], current_objectives[obj.symbol]):
            # the objective should stay as it is
            classification = {obj.symbol: ("=", None)}
        elif not obj.maximize and reference_point[obj.symbol] < current_objectives[obj.symbol]:
            # minimizing objective, reference value smaller: aspiration level
            classification = {obj.symbol: ("<=", reference_point[obj.symbol])}
        elif not obj.maximize and reference_point[obj.symbol] > current_objectives[obj.symbol]:
            # minimizing objective, reference value greater: reservation level
            classification = {obj.symbol: (">=", reference_point[obj.symbol])}
        elif obj.maximize and reference_point[obj.symbol] < current_objectives[obj.symbol]:
            # maximizing objective, reference value smaller: reservation level
            classification = {obj.symbol: (">=", reference_point[obj.symbol])}
        elif obj.maximize and reference_point[obj.symbol] > current_objectives[obj.symbol]:
            # maximizing objective, reference value greater: aspiration level
            classification = {obj.symbol: ("<=", reference_point[obj.symbol])}
        else:
            msg = f"Warning: CUMULUS could not figure out the classification for objective {obj.symbol}."
            raise CumulusError(msg)

        classifications |= classification

    return classifications


def solve_sub_problems(
    problem: Problem,
    current_objectives: dict[str, float],
    reference_point: dict[str, float],
    scalarizations: list[CumulusScalarization],
    scalarization_options: dict | None = None,
    solver: BaseSolver | None = None,
    solver_options: SolverOptions | None = None,
) -> list[SolverResults]:
    r"""Solves one sub-problem per requested scalarization using a partial reference point.

    Unlike the NIMBUS method, CUMULUS does not require the reference point to cover all
    objectives.  Only objectives present in ``reference_point`` are actively scalarized;
    the remaining objectives are left unconstrained.

    Each entry in ``scalarizations`` triggers one solver run:

    - :attr:`CumulusScalarization.CUMULONIMBUS`: derives classifications from
      ``reference_point`` and ``current_objectives``, then solves a partial NIMBUS
      scalarization.  Requires ideal and nadir to be defined for every active objective.
    - :attr:`CumulusScalarization.ASF_PARTIAL_DIFF`: solves a differentiable partial ASF
      directly from ``reference_point``.
    - :attr:`CumulusScalarization.ASF_PARTIAL_NONDIFF`: solves a non-differentiable partial
      ASF (``Max`` form) directly from ``reference_point``.

    Raises:
        CumulusError: ``scalarizations`` is empty.
        CumulusError: ``reference_point`` contains keys that are not objective symbols.
        CumulusError: :attr:`CumulusScalarization.CUMULONIMBUS` is requested but an active
            objective is missing an ideal or nadir value, or ``current_objectives`` does not
            cover all active objectives.

    Args:
        problem (Problem): the problem being solved.
        current_objectives (dict[str, float]): current objective values.  Only entries for
            objectives present in ``reference_point`` are required (and only when
            :attr:`CumulusScalarization.CUMULONIMBUS` is included in ``scalarizations``).
        reference_point (dict[str, float]): partial objective dict with reference point
            values.  Only the objectives listed here participate in the scalarizations.
        scalarizations (list[CumulusScalarization]): ordered list of scalarizations to solve.
            One :class:`SolverResults` is returned per entry.
        scalarization_options (dict | None, optional): optional kwargs forwarded to every
            scalarization function.  Defaults to None.
        solver (BaseSolver | None, optional): solver class to use.  If not given, an
            appropriate solver is determined automatically.  Defaults to None.
        solver_options (SolverOptions | None, optional): options passed to the solver.
            Ignored when ``solver`` is ``None``.  Defaults to None.

    Returns:
        list[SolverResults]: one :class:`SolverResults` per entry in ``scalarizations``,
            in the same order.
    """
    if not scalarizations:
        msg = "scalarizations must contain at least one CumulusScalarization value."
        raise CumulusError(msg)

    valid_symbols = {obj.symbol for obj in problem.objectives}
    invalid = set(reference_point) - valid_symbols
    if invalid:
        msg = f"reference_point contains keys that are not objective symbols: {invalid}."
        raise CumulusError(msg)

    init_solver = solver if solver is not None else guess_best_solver(problem)
    _solver_options = solver_options if solver_options is not None else None

    solutions = []

    for sf in scalarizations:
        match sf:
            case CumulusScalarization.CUMULONIMBUS:
                classifications = infer_classifications(problem, current_objectives, reference_point)
                problem_w_sf, target = add_cumulonimbus_diff(
                    problem, "cumulonimbus_sf", classifications, current_objectives, **(scalarization_options or {})
                )
            case CumulusScalarization.ASF_PARTIAL_DIFF:
                problem_w_sf, target = add_asf_partial_diff(
                    problem, "asf_partial_sf", reference_point, **(scalarization_options or {})
                )
            case CumulusScalarization.ASF_PARTIAL_NONDIFF:
                problem_w_sf, target = add_asf_partial_nondiff(
                    problem, "asf_partial_nondiff_sf", reference_point, **(scalarization_options or {})
                )

        _solver_instance = init_solver(problem_w_sf, _solver_options) if _solver_options else init_solver(problem_w_sf)
        solutions.append(_solver_instance.solve(target))

    return solutions


def generate_starting_point(
    problem: Problem,
    reference_point: dict[str, float] | None = None,
    scalarization_options: dict | None = None,
    solver: BaseSolver | None = None,
    solver_options: SolverOptions | None = None,
) -> SolverResults:
    r"""Generates a starting point for the CUMULUS method.

    Using the given reference point and achievement scalarizing function, finds one pareto
    optimal solution that can be used as a starting point for the CUMULUS method.
    If no reference point is given, ideal is used as the reference point.

    Instead of using this function, the user can provide a starting point.

    Raises:
        CumulusError: the given problem has an undefined ideal or nadir point, or both.

    Args:
        problem (Problem): the problem being solved.
        reference_point (dict[str, float]|None): an objective dictionary with a reference point.
            If not given, ideal will be used as reference point.
        scalarization_options (dict | None, optional): optional kwargs passed to the scalarization function.
            Defaults to None.
        solver (BaseSolver | None, optional): solver used to solve the problem.
            If not given, an appropriate solver will be automatically determined based on the features of `problem`.
            Defaults to None.
        solver_options (SolverOptions | None, optional): optional options passed
            to the `solver`. Ignored if `solver` is `None`.
            Defaults to None.

    Returns:
        SolverResults: the starting point solution.
    """
    ideal = problem.get_ideal_point()
    nadir = problem.get_nadir_point()
    if None in ideal or None in nadir:
        msg = "The given problem must have both an ideal and nadir point defined."
        raise CumulusError(msg)

    if reference_point is None:
        reference_point = {}
    for obj in problem.objectives:
        if obj.symbol not in reference_point:
            reference_point[obj.symbol] = ideal[obj.symbol]

    init_solver = solver if solver is not None else guess_best_solver(problem)
    _solver_options = solver_options if solver_options is not None else None

    # solve ASF
    add_asf = add_asf_diff if problem.is_twice_differentiable else add_asf_nondiff

    problem_w_asf, asf_target = add_asf(problem, "asf", reference_point, **(scalarization_options or {}))

    asf_solver = init_solver(problem_w_asf, _solver_options) if _solver_options else init_solver(problem_w_asf)

    return asf_solver.solve(asf_target)
